config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'employee/show',as: :emp_show
  get 'department/show',as: :dept_show
  get  'company/show',as: :comp_show
  get  'company/edit',as: :change_edit
  patch 'company/update',as: :update_company
  get  'department/edit',as: :dept_edit
  patch 'department/update',as: :update_department
  get  'employee/edit',as: :emp_edit
  patch  'employee/update',as: :update_employee
  get 'employee/delete',as: :delete_emp
  get  'department/delete',as: :delete_dept
  get  'company/delete',as: :delete_comp
  get  'company/new',as: :new_comp 
  get  'department/new',as: :new_dept
  post 'company/create', as: :create_company
  post 'department/create',as: :create_department
  get  'employee/new',as: :new_emp
  post  'employee/create',as: :create_employee

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :departments
	has_many :employees,  through: :departments

end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :company
  has_many :employees
  
  mount_uploader :image, ImageUploader
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def create
      Company.create params.require(:company).permit(:company_name, :location, :company_description)
      redirect_to :action => 'show'
  end


  def show
  	@companies=Company.all
  end	

  def edit
  	@company = Company.find(params[:id])
  	
  end

  def update

    @company = Company.find(params[:company][:id])
      if @company.update_attributes(params.require(:company).permit(:company_name, :location ,:company_description))
         redirect_to :action => 'show'
      else
         render :action => 'edit'
      end

  end

  def delete
    
  	  Company.find(params[:id]).destroy
    	redirect_to :action => 'show'
   end

  def new
   		@companies=Company.new
  end

end

app/controllers/department_controller.rb
class DepartmentController < ApplicationController
  def create
    Department.create params.require(:department).permit(:dept_name, :dept_description,:image)
    respond_to do |format|
    format.html {redirect_to :action => 'show'}
    format.js
    end
  end

  def show
   	@departments=Department.all
  end

  def edit
  	@department = Department.find(params[:id])
  end

  def update
      @department = Department.find(params[:department][:id])
      if @department.update_attributes(params.require(:department).permit(:dept_name ,:dept_description,:company_id))
        redirect_to :action => 'show'
      else
        render :action => 'edit'
      end

  end  

  def delete
   	  Department.find(params[:id]).destroy
      respond_to do |format|
      format.html {redirect_to :action => 'show'}
      format.js
      end
  end

  def new
   	   @department=Department.new
  end	
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
	
  def create
    Employee.create params.require(:employee).permit(:emp_name, :emp_address, :age ,:working_location ,:salary)
    redirect_to :action => 'show'
  end

	def show
  		@employees=Employee.all
  end	

  def edit
      @employee = Employee.find(params[:id])
      
  end

  def update

    @employee = Employee.find(params[:employee][:id])
    if @employee.update_attributes(params.require(:employee).permit(:emp_name,:emp_address,:age ,:working_location ,:salary, :department_id))
         redirect_to :action => 'show'
    else
         render :action => 'edit'
    end

  end  

  def delete
   		Employee.find(params[:id]).destroy
      	redirect_to :action => 'show'
  end

  def new
   		@employee=Employee.new
  end	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
def index
end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/company/edit.html.erb
<%= form_for @company, url: {action: "update"}  do |f|  %>
<%= f.hidden_field :id %>
company_name: <%= f.text_field :company_name %><br />
Location : <%= f.text_field :location%><br />
company_description :<%= f.text_field :company_description %><br />
<%= f.submit "save" %>
<%end%>

app/views/company/new.html.erb
<h1> new record</h1>
<%= form_for Company.new, url: {action: "create"} do |f| %>
	<p><label for="company name">company_name</label>:
	<%= f.text_field :company_name %></p>
	<p><label for="location">location</label>:
	<%= f.text_field :location %></p>
	<p><label for="company description">company_description</label>:
	<%= f.text_field :company_description %></p>
	<%= f.submit "Create" %>
<% end %>

app/views/company/show.html.erb
<h1>Company details</h1>
<% @companies.each do |c| %>
    <div><p>company id:-<%=  c.id %></p></div>
	<div><p>company name :-<%=  c.company_name %></p></div>
	<div><p>company description:-<%=  c.company_description %></p></div>
	<div><p>location:-<%=c.location %></p></div>
	<%= link_to "edit",change_edit_path(:id => c.id) %><br />
	<%= link_to "delete",delete_comp_path(:id => c.id) %><br />
<% end %><br />
	<%= link_to "new record",new_comp_path%><br />

app/views/department/create.js.erb
$('#department-form').html("<%= j (render 'form') %>");
$('#department-form').slideUp(350);

app/views/department/edit.html.erb
<%= form_for @department, url: {action: "update"}  ,:remote => true do |f|  %>
    <%= f.hidden_field :id %>
	dept_name: <%= f.text_field :dept_name  %><br />
	dept_description: <%= f.text_field :dept_description  %><br />
	<%= f.select :company_id, Company.all.map { |u| [u.company_name, u.id] }, { :prompt => "Please Select" } %>
	<%= f.submit "save" %>
<%end%>

app/views/department/new.html.erb
<h1> new record</h1>
<%= form_for Department.new, url: {action: "create"} ,remote :true do |f| %>
<p><label for="department name">dept_name</label>:
<%= f.text_field :dept_name %></p>
<p><label for="dept_description">dept_description</label>:
<%= f.text_field :dept_description %></p>
<p><label for="department"></label>
<%= f.file_field :image %></p>
<%= f.submit "Create" %>
<% end %>

app/views/department/show.html.erb
<h1>Department details</h1>
<% @departments.each do |dept| %>
    <div><p>department id:-<%=  dept.id %></p></div>
    <div><p>department name :-<%=  dept.dept_name %></p></div>
	<div><p>department description:-<%=  dept.dept_description %></p></div>
	<%= image_tag dept.image.thumb %>
    <%= link_to "edit",dept_edit_path(:id =>dept.id) ,:remote => true %><br />
	<%= link_to "delete",delete_dept_path(:id =>dept.id) %><br />
<% end %><br />
<%= link_to "new record",new_dept_path%><br />

app/views/employee/edit.html.erb
<%= form_for @employee, url: {action: "update"}  do |f|  %>
  <%= f.hidden_field :id %>
  emp_name: <%= f.text_field :emp_name %><br />
  emp_address: <%= f.text_field :emp_address%><br />
  age <%= f.text_field :age%><br />
  working_location <%= f.text_field :working_location%><br />
  salary <%= f.text_field :salary%><br />
 
  <%= f.select :department_id, Department.all.map { |u| [u.dept_name, u.id] }, { :prompt => "Please Select" } %>

  <%= f.submit "save" %>
 
<%end%>

app/views/employee/new.html.erb
<h1> new record</h1>
<%= form_for Employee.new, url: {action: "create"} do |f| %>
<p><label for="employee name">emp_name</label>:
<%= f.text_field :emp_name %></p>
<p><label for="employee address">emp_address</label>:
<%= f.text_field :emp_address%></p>
<p><label for="age">age</label>:
<%= f.text_field :age%></p>
<p><label for="working_location">working_location</label>:
<%= f.text_field :working_location%></p>
<p><label for="salary">salary</label>:
<%= f.text_field :salary%></p>
<%= f.submit "Create" %>
<% end %>

app/views/employee/show.html.erb
<h1>Employee details</h1>
<% @employees.each do |emp| %>
<div><p>employee id:-<%=  emp.id %></p></div>
<div><p>employee name :-<%=  emp.emp_name %></p></div>
<div><p>employee address:-<%=  emp.emp_address %></p></div>
<div><p>employee age:-<%=  emp.age %></p></div>
<div><p>employee location:-<%=  emp.working_location %></p><div>
<div><p>employee salary:-<%=  emp.salary%></p></div>
<%= link_to "edit",emp_edit_path(:id =>emp.id) %><br />
<%= link_to "delete",delete_emp_path(:id =>emp.id) %><br />
<% end %><br/>
<%= link_to "new record",new_emp_path%><br />
        

app/views/home/index.html.erb
<p>Choose the link to follow</p>
<%= link_to "Employee" , emp_show_path %><br />
<%=  link_to "Department" , dept_show_path %><br />
<%= link_to "Company" , comp_show_path %><br />

	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UseOfAssociation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>